name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          args: --exclude=Assignment1/
      - name: API Keys in Github Secrets
        run: echo "API keys are set"

  react-ci:
    runs-on: ubuntu-latest
    name: React-Continuous-Integration
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
        working-directory: get-ur-tickets/
      - name: ESLint
        run: npm run Lint
      - name: Build the project
        run: npm run build
