name: Continuous-Integration

on: [push, pull_request]

env:
  TICKET_API_KEY: ${{ secrets.TICKET_API_KEY }}
  SERP_API_KEY: ${{ secrets.SERP_API_KEY }}

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Python-CI
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests  # fails build if requests isnt installed
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          args: --exclude=Assignment1/
      - name: API Keys in Github Secrets
        run: | 
          echo "API keys are set"
          python backend/processing.py

  react-ci:
    runs-on: ubuntu-latest
    name: React-CI
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
        working-directory: get-ur-tickets/
      - name: ESLint
        run: npm run lint
        working-directory: get-ur-tickets/
      - name: Build the project
        run: npm run build
        working-directory: get-ur-tickets/
